creation_rules:
  # Encrypt .env files and .env.encrypted
  - path_regex: \.env\.encrypted$|\.env$|secrets\.env$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Encrypt SSH keys and .ssh.encrypted
  - path_regex: \.ssh\.encrypted$|\.ssh$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - path_regex: secrets\.encrypted\..*
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
