creation_rules:
  # Encrypt data.yml (SSH keys before encryption)
  - path_regex: data\\data\.yml$|data/data\.yml$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Encrypt .env files and .env.encrypted
  - path_regex: \.env\.encrypted\.(yml|yaml|env)$|\.env\.encrypted$|\.env$|secrets\.env$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Encrypt SSH keys and .ssh.encrypted
  - path_regex: \.ssh\.encrypted\.(yml|yaml|env)$|\.ssh\.encrypted$|\.ssh$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - path_regex: secrets\.encrypted\.(yml|yaml|env)$|secrets\.encrypted\..*
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
